// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://facdtytdhsrtmfyzlhsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhY2R0eXRkaHNydG1meXpsaHNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3MTIxNjcsImV4cCI6MjA5MDI4ODE2N30.9M2z0tsFb_gh0FC4mfFnWHf6mkGF1suzQmgivnhZsqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);